/**
 * The game rules, as pure functions.
 *
 * Each one is the *definition* of a behaviour. Several of them are also
 * *enforced* somewhere else — the paywall and the sticker award run in
 * PocketBase hooks on the server (plan §3), and the copies the client calls
 * exist only so the UI can respond instantly. Where a rule matters for
 * security, its doc comment says where the enforcement lives.
 */

export {
  BILLING_PERIODS,
  ENTITLING_SUBSCRIPTION_STATUSES,
  GUARDIAN_ONLY_AGE_BANDS,
  formatPricePence,
  isBillingPeriod,
  isPaidPlan,
  planPeriodLabel,
  planPricePence,
  requiredPayerKind,
  requiresGuardianPayer,
  statusEntitles,
  subscriptionRefusal,
  upgradeRouteFor,
  yearlySavingLabel,
  yearlySavingMonths,
  type BillingPeriod,
  type PayerKind,
  type UpgradeRoute,
} from './billing';
export {
  canLogChallenge,
  challengeProgress,
  challengeRangeLabel,
  challengeRewardSticker,
  challengeState,
  challengesFor,
  challengesOverlap,
  isDayInChallenge,
  liveChallenge,
  overlappingChallenges,
  type ChallengeProgress,
} from './challenges';
export {
  EVENT_KIND_COLORS,
  EVENT_KIND_IDS,
  eventDateBlock,
  eventKindColor,
  eventKindsPresent,
  eventsFor,
  filterEvents,
  isEventPast,
  sortedEvents,
  type EventDateBlock,
  type EventQuery,
} from './events';
export {
  AGE_BANDS,
  CONSENT_APPROVAL_WINDOW_DAYS,
  CONSENT_LIMITED_ALLOWS,
  CONSENT_LIMITED_DENIES,
  CONSENT_LIMITED_STATES,
  DEFAULT_CONSENT_AGE,
  EEA_CONSENT_AGE,
  EEA_COUNTRIES,
  EEA_LOWERED_CONSENT_AGES,
  UNDER_13_DECLINED_COUNTRIES,
  advanceBand,
  ageOn,
  approvalExpired,
  bandForAge,
  birthdayOn,
  canWhileConsentLimited,
  canWithConsent,
  consentAge,
  consentLapsesOn,
  consentRequired,
  countryOf,
  declareAge,
  initialConsentState,
  isConsentLimited,
  refreshConsent,
  signupOutcome,
  type AgeBand,
  type AgeDeclaration,
  type ConsentState,
  type RiderCapability,
  type SignupOutcome,
} from './consent';
export {
  CREW_NAME_MAX_LENGTH,
  CREW_NAME_MIN_LENGTH,
  INVITE_CODE_ALPHABET,
  INVITE_CODE_GROUP,
  INVITE_CODE_LENGTH,
  INVITE_EXPIRY_DAYS,
  INVITE_MAX_USES,
  MAX_OWNED_CREWS,
  SUPERVISED_MIN_DIFF,
  crewActivityLine,
  crewNameProblem,
  crewSlug,
  formatInviteCode,
  isValidInviteCode,
  normaliseInviteCode,
  sortCrewActivity,
  supervisedTricks,
  type CrewActivityItem,
  type CrewActivityKind,
} from './crew';
export {
  TRICK_SORTS,
  TRICK_STATUS_FILTERS,
  activeFilterCount,
  filterTricks,
  prereqTricks,
  sortTricks,
  trickMatchesSearch,
  trickMatchesStatus,
  tricksUnlockedBy,
  type LibraryQuery,
  type TrickSort,
  type TrickStatusFilter,
} from './library';
export {
  firstLanded,
  landedByMonth,
  latestLanded,
  logEntriesForTrick,
  type LandedMonth,
  type LogOptions,
} from './log';
export {
  MONTH_LABELS,
  insightsVisible,
  monthKeyLabel,
  monthKeysBack,
  planIncludesInsights,
  progressInsights,
  skillTree,
  stageBreakdown,
  trickDepth,
  type CategoryTrend,
  type NextTrickSuggestion,
  type PersonalRecords,
  type ProgressInsights,
  type ProgressInsightsInput,
  type SkillState,
  type SkillTreeBranch,
  type SkillTreeNode,
  type SkillTreeTier,
  type StageBreakdown,
  type StageCount,
} from './progress';
export {
  goalLabel,
  goalsFor,
  handleCandidates,
  handleFromName,
  handleProblem,
  isValidCustomGoal,
  isValidHandle,
  normaliseHandle,
} from './profile';
export {
  REPORT_DETAIL_MAX,
  REPORT_MAX_OPEN,
  REPORT_MAX_PER_WINDOW,
  REPORT_REASONS,
  REPORT_REASON_IDS,
  REPORT_SUBJECTS,
  REPORT_SUBJECT_IDS,
  REPORT_WINDOW_MINUTES,
  isEmailish,
  isReportReason,
  isReportSubject,
  reportProblems,
  reportReasonLabel,
  reportSubjectLabel,
  type ReportDraft,
  type ReportReasonId,
  type ReportSubjectId,
} from './reports';
export {
  SPOT_MAX_TAGS,
  SPOT_NAME_MAX_LENGTH,
  SPOT_SUBMISSION_MAX_PENDING,
  SPOT_SUBMISSION_MAX_PER_WINDOW,
  SPOT_SUBMISSION_WINDOW_MINUTES,
  SPOT_TAG_MAX_LENGTH,
  SPOT_TOWN_MAX_LENGTH,
  distanceLabel,
  distanceMiles,
  filterSpots,
  hasCoords,
  isValidLatLng,
  mapsLink,
  parseCoords,
  parseSpotLocation,
  readSpotSubmission,
  sortSpotsByDistance,
  spotLatLng,
  spotLocationMessage,
  spotMatchesSearch,
  spotMatchesSport,
  spotSubmissionProblems,
  splitSpotTags,
  type SpotLike,
  type SpotLocationRefusal,
  type SpotLocationResult,
  type SpotQuery,
  type SpotSubmission,
  type SpotSubmissionDraft,
  type SpotSubmissionProblems,
} from './spots';
export { computeSportStats, computeStats, sportsOf, type StatsCatalogue } from './stats';
export {
  STICKER_RULES,
  earnedStickerIds,
  evaluateSticker,
  newlyEarnedStickerIds,
  stickerCondition,
  stickerRule,
  stickerScope,
  stickersFor,
} from './stickers';
export {
  NUDGE_QUIET_FROM_HOUR,
  NUDGE_QUIET_UNTIL_HOUR,
  canNudge,
  isQuietHours,
  riderHour,
} from './nudges';
export {
  STREAK_GRACE_DAYS,
  WEEKLY_RIDE_TARGET,
  WEEKLY_STREAK_GRACE_WEEKS,
  currentStreak,
  currentWeeklyStreak,
  logRide,
  logWeeklyRide,
  riderToday,
  riderWeekStart,
  rodeToday,
  streakStrip,
  weeklyEncouragement,
  weeklyProgress,
  weeklyProgressLabel,
  weeklyRideCount,
  weeklyStreakLabel,
  weeklyTargetMet,
  type RideResult,
  type RiderClock,
  type StreakState,
  type WeeklyProgress,
  type WeeklyRideResult,
  type WeeklyStreakOptions,
  type WeeklyStreakState,
} from './streak';
export {
  DEFAULT_TIMEZONE,
  MONTH_NAMES,
  WEEKDAY_NAMES,
  WEEK_STARTS_ON,
  addDays,
  compareDayKeys,
  daysBetween,
  formatDayLong,
  isDayKey,
  isDayWithin,
  monthName,
  toDayKey,
  weekEnd,
  weekStart,
  weekdayName,
  weeksBetween,
} from './time';
export {
  FREE_MAX_DIFF,
  isLandedStage,
  isTrickFree,
  isTrickLanded,
  isTrickLocked,
  isTrickUnlocked,
  missingPrereqs,
  openTricks,
  planUnlocksPaidTricks,
  sportOf,
  suggestedNextTricks,
  trickById,
  tricksFor,
  tricksInCategory,
} from './tricks';
