#!/usr/bin/env node
/**
 * Fetch France's skateparks from the Ministry of Sport's open-data API and
 * write them to `src/imports/france.data.ts`.
 *
 *   pnpm --filter @landit/db import:france
 *
 * **A snapshot, on purpose.** The seed reads the committed file, never the
 * network: a seed run on the live box must not depend on a French government
 * server answering, and a reviewer must be able to read what is about to be
 * written. Re-running this regenerates the file and stamps it with today's date,
 * which is the date the credit line under the spots map has to show — Licence
 * Ouverte 2.0 asks for the source's name and when it was last updated.
 *
 * **What is kept is the source's own words, not ours.** The file holds the raw
 * fields the mapping needs (`src/imports/france.ts` turns them into spot rows),
 * so a change to the naming rule or the territory rule is a code change with a
 * unit test, not a re-fetch. Rows with no coordinates are dropped here because
 * there is nothing to map; everything else is left for the mapping to judge.
 *
 * Source: https://equipements.sports.gouv.fr — dataset `data-es-agregation`,
 * `equipement_type = "Skatepark"`. The joined view is the one with location
 * fields; the bare `data-es-equipement` dataset has none (issue #362).
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import type { FranceSourceRow } from '../src/imports/france.ts';

const API =
  'https://equipements.sports.gouv.fr/api/explore/v2.1/catalog/datasets/data-es-agregation/records';
const PAGE = 100;

interface ApiRecord {
  readonly equipement_numero: string | null;
  readonly installation_nom: string | null;
  readonly equipement_nom: string | null;
  readonly installation_commune: string | null;
  readonly installation_cp: string | null;
  readonly installation_adresse: string | null;
  readonly equipement_coordonnees: string | null;
  readonly equipement_nature: string | null;
  readonly equipement_aire_nature_sol: string | null;
}

interface ApiPage {
  readonly total_count: number;
  readonly results: readonly ApiRecord[];
}

async function page(offset: number): Promise<ApiPage> {
  const url = new URL(API);
  url.searchParams.set('where', 'equipement_type="Skatepark"');
  url.searchParams.set('limit', String(PAGE));
  url.searchParams.set('offset', String(offset));
  url.searchParams.set('order_by', 'equipement_numero');
  const response = await fetch(url, { headers: { accept: 'application/json' } });
  if (!response.ok) throw new Error(`${url} → ${response.status}`);
  return (await response.json()) as ApiPage;
}

const text = (value: string | null | undefined): string => (value ?? '').trim();

/** `"48.68798, 1.83583"` → `[48.68798, 1.83583]`, or `null` for anything else. */
function coords(value: string | null): readonly [number, number] | null {
  const match = /^\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*$/.exec(value ?? '');
  if (!match) return null;
  const lat = Number(match[1]);
  const lng = Number(match[2]);
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) return null;
  if (Math.abs(lat) > 90 || Math.abs(lng) > 180) return null;
  return [lat, lng];
}

const rows: FranceSourceRow[] = [];
let fetched = 0;
let noCoords = 0;
let total = Infinity;

for (let offset = 0; offset < total; offset += PAGE) {
  const result = await page(offset);
  total = result.total_count;
  fetched += result.results.length;
  for (const record of result.results) {
    const point = coords(record.equipement_coordonnees);
    if (!point) {
      noCoords += 1;
      continue;
    }
    rows.push([
      text(record.equipement_numero),
      text(record.installation_nom),
      text(record.equipement_nom),
      text(record.installation_commune),
      text(record.installation_cp),
      text(record.installation_adresse),
      point[0],
      point[1],
      text(record.equipement_nature),
      text(record.equipement_aire_nature_sol),
    ]);
  }
  process.stderr.write(`  ${fetched} / ${total}\n`);
  if (result.results.length === 0) break;
}

// Stable order regardless of what the API chose, so a re-fetch with no data
// change produces no diff.
rows.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));

const today = new Date().toISOString().slice(0, 10);
const here = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(here, '..', 'src', 'imports', 'france.data.ts');

const header = `/**
 * GENERATED by \`pnpm --filter @landit/db import:france\` on ${today} — do not edit.
 *
 * ${rows.length} skateparks with coordinates, from the ${fetched} records the
 * French Ministry of Sport's equipment census returned for
 * \`equipement_type = "Skatepark"\` (${noCoords} had no coordinates and were
 * dropped). Licence Ouverte / Open Licence 2.0 (Etalab), attribution only.
 * Field order is \`FranceSourceRow\` in \`./france.ts\`.
 */
import type { FranceSourceRow } from './france';

/** The day this snapshot was taken, for the credit line under the spots map. */
export const FRANCE_SNAPSHOT_DATE = '${today}';

// prettier-ignore
export const FRANCE_SOURCE_ROWS: readonly FranceSourceRow[] = [
`;
const body = rows.map((row) => `  ${JSON.stringify(row)},`).join('\n');
await writeFile(out, `${header}${body}\n];\n`, 'utf8');

process.stderr.write(
  `Wrote ${rows.length} rows to ${path.relative(process.cwd(), out)} ` +
    `(${fetched} fetched, ${noCoords} without coordinates).\n`,
);
