import { SPOTS, SPOT_SOURCES, distanceMiles, type Spot } from '@landit/core';

import { FRANCE_SOURCE_ROWS } from './france.data';

/**
 * France's skateparks, from the Ministry of Sport's equipment census to spot
 * rows the seed can write (issue #362).
 *
 * **This module is the seeder's and nobody else's.** The rows live in
 * `france.data.ts`, generated by `scripts/import-france.mts`, and never in
 * `packages/core/src/data/spots.ts` — that file is four thousand lines of
 * places a session opened a page for, and three thousand machine-mapped rows
 * would bury them. Nothing on a screen imports from here; the app reads the
 * database, and the database is where these become spots.
 *
 * **Everything here is pure**, so every rule below has a unit test against the
 * real snapshot: the naming rule, the territory rule, the roof rule and the
 * duplicate rule are each a function of the row and nothing else.
 *
 * ---
 *
 * **What the census can say, and what it cannot.** It records a point, a
 * commune, a street, whether the equipment is under a roof
 * (`equipement_nature`) and what its floor is made of. It does not record
 * closure, and it does not say a word about scooters or BMX — "Skatepark" is
 * the type, and that is all. So every row arrives `operating: 'unknown'` and
 * `sports: ['skate']`: the house rule is that a sport is listed only where the
 * venue, the council or an agreement says it is allowed (`SPOTS`), and a
 * census saying nothing is not a council saying yes. A staff edit is the only
 * thing that changes either, which is why the seed never overwrites these rows
 * once they exist (`onExisting: 'skip'` in `seed.ts`).
 *
 * **The naming rule.** Most rows are called some spelling of "skate park", and a
 * straight copy would put hundreds of identical cards on the map. A name is
 * *generic* when nothing survives once the words for a facility are removed —
 * "SKATE PARK", "Complexe sportif municipal", "Terrain multisports" all
 * reduce to nothing, while "STADE JEAN MOULIN" keeps "jean moulin" and
 * "Skate park Vinaigrerie" keeps "vinaigrerie". A generic row is named
 * "Skatepark" and the town does the rest — *Skatepark, Dreux* — and a
 * non-generic installation name is used as it is, re-cased only when the
 * source shouted or whispered it (all caps, all lower), because a name a human
 * cased by hand is a name a human meant. Where two rows in one commune would
 * still share a name, the equipment's own name is tried if it says something,
 * then the street with its house number stripped, then an ordinal — and every
 * candidate has to fit the column.
 *
 * **The duplicate rule.** The census lists a park's *pieces* as rows — "Skate
 * park", "Skate park 2" … "Skate park 8" at one point on one street — because
 * it counts equipment, not places. Rows in one commune at the same point to
 * four decimal places (about eleven metres) are one place on a map, so they
 * collapse to one spot, indoor if any piece is. A row within about 160
 * metres of a hand-researched spot is dropped too: that park is already on the
 * map with a page somebody checked, and a second pin would be the same place
 * with a worse name.
 *
 * **The territory rule (#328, decision pending — see the PR).** Forty-odd rows
 * are overseas. They carry their own territory's name — Réunion, French
 * Guiana, New Caledonia — rather than "France", derived from the postcode
 * prefix (`installation_cp`), which is more reliable than the region column
 * that fourteen of them leave blank. That matches New Caledonia as it already
 * ships in `SPOTS`: a rider in Nouméa would never look under France for their
 * park. If the owner rules the other way, `territoryFor` is the one function
 * to change.
 */

/**
 * One source record, reduced to the fields the mapping reads, in this order:
 * `equipement_numero`, `installation_nom`, `equipement_nom`,
 * `installation_commune`, `installation_cp`, `installation_adresse`, lat, lng,
 * `equipement_nature`, `equipement_aire_nature_sol`.
 */
export type FranceSourceRow = readonly [
  id: string,
  installationName: string,
  equipmentName: string,
  commune: string,
  postcode: string,
  street: string,
  lat: number,
  lng: number,
  nature: string,
  surface: string,
];

const SOURCE = SPOT_SOURCES['fr-sports-gouv'];

/** `spots.name` is `max: 80` (`1786838400_init_collections.js`). */
const NAME_MAX = 80;
/** `spots.address` is `max: 200`. */
const ADDRESS_MAX = 200;
/** The name a generic row gets; the town disambiguates on the card. */
const GENERIC_NAME = 'Skatepark';
/** Same place, to four decimal places — about eleven metres. */
const POINT_PRECISION = 4;
/**
 * A row this close to a hand-researched spot is that spot — about 160 metres,
 * which is a sports complex's width. The census plots a park at its
 * installation's entrance and a session plots it at the bowl, and the two
 * were 85 metres apart for Jules Noël in Paris.
 */
const CURATED_RADIUS_MILES = 0.1;

/* --------------------------------------------------------------- words -- */

/**
 * The words a facility is described with, in the census's own vocabulary.
 * A name made only of these says *what* a place is and never *which* — remove
 * them and a real name keeps something, a generic one keeps nothing.
 */
// prettier-ignore
const FACILITY_WORDS = new Set([
  // the thing itself
  'skate', 'skatepark', 'skateparc', 'skateboard', 'skating', 'park', 'parks', 'parc', 'parcs',
  'parck', 'board', 'boarding', 'roller', 'rollers', 'bmx', 'pumptrack', 'pump', 'track', 'bowl',
  'street', 'rampe', 'rampes', 'piste', 'pistes', 'glisse', 'glisses', 'trottinette', 'stake',
  'skat', 'skatte', 'padel', 'boulodrome', 'agorespace', 'agoraespace', 'citypark', 'bikepark',
  'rollerpark', 'flowpark', 'ludespace', 'cosec', 'piscine', 'eps',
  // the kinds of place it sits in
  'complexe', 'complexes', 'complex', 'espace', 'espaces', 'ensemble', 'plateau', 'plateaux', 'terrain',
  'terrains', 'aire', 'aires', 'zone', 'zones', 'plaine', 'plaines', 'base', 'salle', 'salles',
  'centre', 'stade', 'stades', 'gymnase', 'halle', 'city', 'plan', 'site', 'equipement',
  'equipements', 'installation', 'installations', 'jardin', 'jardins', 'square', 'place',
  'village', 'bourg', 'mairie', 'ecole', 'ecoles', 'college', 'lycee', 'quartier',
  // the adjectives
  'sportif', 'sportifs', 'sportive', 'sportives', 'sport', 'sports', 'municipal', 'municipale',
  'municipaux', 'communal', 'communale', 'intercommunal', 'intercommunale', 'multisport',
  'multisports', 'omnisport', 'omnisports', 'polyvalent', 'polyvalente', 'multi', 'activite',
  'activites', 'animation', 'animations', 'proximite', 'couvert', 'couverte', 'indoor',
  'outdoor', 'exterieur', 'interieur', 'mini', 'petit', 'petite', 'grand', 'grande', 'nouveau',
  'nouvelle', 'nouvelles', 'ancien', 'ancienne', 'urbain', 'urbaine', 'public', 'publique',
  'libre',
  // what else is there
  'jeux', 'jeu', 'loisir', 'loisirs', 'detente', 'football', 'foot', 'basket', 'tennis',
  'rugby', 'boules', 'petanque', 'jeunes', 'jeunesse', 'enfants', 'eau', 'famille', 'nature',
  'verte', 'vert', 'evolution', 'freestyle', 'urban', 'fun',
  // the glue
  'de', 'du', 'des', 'la', 'le', 'les', 'l', 'd', 'et', 'a', 'au', 'aux', 'sur', 'sous', 'en',
  'pour', 'par', 'dans', 'un', 'une', 'the', 'of', 'and', 'n', 'no', 'er', 'e', 'eme', 'bis',
]);

/** Lowercase, accents folded, punctuation to spaces: the words and nothing else. */
export function foldWords(text: string): string[] {
  return text
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(Boolean);
}

/**
 * Does this name say *which* place, or only *what kind*?
 *
 * Generic: "SKATE PARK", "Skate park 2", "Complexe sportif municipal",
 * "Terrain multisports", "Aire de jeux et loisirs". Not generic: "STADE JEAN
 * MOULIN", "Skate park Vinaigrerie", "Aire de jeux et loisirs Capriata d'Orba".
 * A bare number is generic — it is the census counting pieces.
 */
export function isGenericName(text: string): boolean {
  return foldWords(text).every((word) => FACILITY_WORDS.has(word) || /^\d+$/.test(word));
}

/** Words kept lowercase inside a French title, unless they start it. */
// prettier-ignore
const PARTICLES = new Set([
  'de', 'du', 'des', 'la', 'le', 'les', 'et', 'à', 'a', 'au', 'aux', 'sur', 'sous', 'en',
  'pour', 'par', 'dans', 'un', 'une', 'd', 'l',
]);

/** Words the census writes in caps that stay that way. */
const ACRONYMS = new Set(['bmx', 'mjc', 'zac', 'zae', 'rd', 'rn', 'egp', 'mlk', 'usep']);

function capitalise(word: string): string {
  return word.charAt(0).toLocaleUpperCase('fr-FR') + word.slice(1);
}

function titleWord(word: string, first: boolean): string {
  const lower = word.toLocaleLowerCase('fr-FR');
  // "d'orba" → "d'Orba", "l'étang" → "l'Étang"; the particle stays lower
  // unless it opens the name.
  const elided = /^([dl])['’](.+)$/.exec(lower);
  if (elided) {
    const [, particle, rest] = elided;
    return `${first ? capitalise(particle!) : particle}’${capitalise(rest!)}`;
  }
  if (ACRONYMS.has(lower)) return lower.toUpperCase();
  if (!first && PARTICLES.has(lower)) return lower;
  return capitalise(lower);
}

/**
 * Title case for a name the source shouted or whispered — "STADE JEAN MOULIN"
 * → "Stade Jean Moulin", "skate park de la gare" → "Skate Park de la Gare".
 * Hyphenated words are cased on both sides ("Saint-Joseph").
 *
 * "Shouted" tolerates a lowercase particle ("TERRAIN PHILOMENE DUCHAMP et
 * SKATEPARK" is still shouting), and "whispered" includes sentence case
 * ("Skate park valgelas" — one capital, typed by habit, on a name that has a
 * proper noun in it). Anything else is left exactly as it came: a human cased
 * it, and "SkatePark Saint-Joseph" is what they meant even if it is not what
 * we would write.
 */
export function recaseName(text: string): string {
  const tidy = text.replace(/\s+/g, ' ').trim();
  const words = tidy.split(/[\s-]+/).filter((word) => !PARTICLES.has(word.toLowerCase()));
  const letters = words.join('').replace(/[^\p{L}]/gu, '');
  if (!letters) return tidy;
  const shouted = letters === letters.toLocaleUpperCase('fr-FR');
  const whispered = letters.slice(1) === letters.slice(1).toLocaleLowerCase('fr-FR');
  if (!shouted && !whispered) return tidy;

  return tidy
    .split(' ')
    .map((word, i) =>
      word
        .split('-')
        .map((part, j) => titleWord(part, i === 0 && j === 0))
        .join('-'),
    )
    .join(' ');
}

/* ----------------------------------------------------------- territory -- */

/**
 * The country name a postcode belongs to. Overseas France has its own prefixes
 * (`97x`, `98x`); everything else is metropolitan. The names are spelled as
 * `SPOT_COUNTRY_BY_CODE` in `@landit/core` spells them, which is what makes a
 * Réunion rider's parks lead their list.
 */
export function territoryFor(postcode: string): string {
  switch (postcode.trim().slice(0, 3)) {
    case '971':
      return 'Guadeloupe';
    case '972':
      return 'Martinique';
    case '973':
      return 'French Guiana';
    case '974':
      return 'Réunion';
    case '975':
      return 'St Pierre & Miquelon';
    case '976':
      return 'Mayotte';
    case '977':
      return 'St Barthélemy';
    case '978':
      return 'St Martin';
    case '986':
      return 'Wallis & Futuna';
    case '987':
      return 'French Polynesia';
    case '988':
      return 'New Caledonia';
    default:
      return 'France';
  }
}

/* ---------------------------------------------------------------- roof -- */

/** `equipement_nature` values that mean the park is under cover. */
const COVERED = new Set(['Intérieur', 'Extérieur couvert', 'Découvrable']);

/**
 * Under a roof? `Intérieur` is a hall, `Extérieur couvert` a canopy,
 * `Découvrable` a roof that opens — a rider stays dry under all three.
 * Everything else, including a blank, is not *known* to be covered, which is
 * what `false` means in `spots.indoor` (`1788912000_spot_indoor_and_operating.js`).
 */
export function isCovered(nature: string): boolean {
  return COVERED.has(nature.trim());
}

/* ---------------------------------------------------------------- town -- */

/**
 * "Paris 18e Arrondissement" → "Paris"; "Lyon 1er Arrondissement" → "Lyon".
 * The arrondissement is a postal fact and the postcode still carries it; the
 * town a rider reads on a card is the city. The address keeps the full commune.
 */
export function townFor(commune: string): string {
  return commune.replace(/\s+\d+(?:er|e|ème)\s+Arrondissement$/i, '').trim();
}

/** "6 rue du château" → "rue du château"; "Chemin de la Scierie" unchanged. */
export function streetName(street: string): string {
  return street
    .replace(/^\s*\d+[\s,]*(?:bis|ter|[a-z])?[\s,]+/i, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/* ------------------------------------------------------------- mapping -- */

/** A group of census rows that are one place. */
export interface FrancePlace {
  readonly rows: readonly FranceSourceRow[];
  readonly lat: number;
  readonly lng: number;
  readonly commune: string;
  readonly postcode: string;
  readonly street: string;
  readonly indoor: boolean;
}

const pointKey = (lat: number, lng: number): string =>
  `${lat.toFixed(POINT_PRECISION)},${lng.toFixed(POINT_PRECISION)}`;

const byId = (a: FranceSourceRow, b: FranceSourceRow): number =>
  a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0;

/** Rows in one commune at one point are one place, in id order. */
export function collapsePlaces(rows: readonly FranceSourceRow[]): readonly FrancePlace[] {
  const places = new Map<string, FranceSourceRow[]>();
  for (const row of [...rows].sort(byId)) {
    const key = `${row[3]}|${pointKey(row[6], row[7])}`;
    const group = places.get(key);
    if (group) group.push(row);
    else places.set(key, [row]);
  }
  return [...places.values()].map((group) => {
    const first = group[0]!;
    return {
      rows: group,
      lat: first[6],
      lng: first[7],
      commune: first[3],
      postcode: first[4],
      street: group.map((row) => row[5]).find(Boolean) ?? '',
      indoor: group.some((row) => isCovered(row[8])),
    };
  });
}

/** The name a place is called before any collision is resolved. */
export function baseName(place: FrancePlace): string {
  for (const row of place.rows) {
    if (!isGenericName(row[1])) return recaseName(row[1]);
  }
  for (const row of place.rows) {
    if (!isGenericName(row[2])) return recaseName(row[2]);
  }
  return GENERIC_NAME;
}

/**
 * The names to try, in order, when two places in one town share a base name:
 * a distinctive equipment name, then the street, then nothing — the caller
 * falls back to an ordinal. Every candidate is already checked for width.
 */
function alternatives(place: FrancePlace, base: string): string[] {
  const out: string[] = [];
  for (const row of place.rows) {
    if (!isGenericName(row[2])) out.push(recaseName(row[2]));
  }
  const street = streetName(place.street);
  if (street && !isGenericName(street)) out.push(`${base} ${recaseName(street)}`);
  return out.filter((name) => name.length <= NAME_MAX && name !== base);
}

/** Every name in a town is unique, and every one fits the column. */
export function nameSpots(places: readonly FrancePlace[]): readonly string[] {
  const bases = places.map(baseName);
  const byTown = new Map<string, number[]>();
  places.forEach((place, i) => {
    const key = `${townFor(place.commune)}|${bases[i]}`;
    const group = byTown.get(key);
    if (group) group.push(i);
    else byTown.set(key, [i]);
  });

  const names: string[] = [...bases];
  const takenByTown = new Map<string, Set<string>>();
  const taken = (place: FrancePlace): Set<string> => {
    const town = townFor(place.commune);
    let set = takenByTown.get(town);
    if (!set) {
      set = new Set();
      takenByTown.set(town, set);
    }
    return set;
  };

  // Uncontested names first, so a contested place cannot take one of them.
  for (const group of byTown.values()) {
    if (group.length === 1) taken(places[group[0]!]!).add(bases[group[0]!]!);
  }
  for (const group of byTown.values()) {
    if (group.length === 1) continue;
    for (const i of group) {
      const place = places[i]!;
      const base = bases[i]!;
      const used = taken(place);
      let chosen = alternatives(place, base).find((name) => !used.has(name));
      for (let n = 2; chosen === undefined; n += 1) {
        const ordinal = `${base} ${n}`;
        if (ordinal.length <= NAME_MAX && !used.has(ordinal)) chosen = ordinal;
      }
      used.add(chosen);
      names[i] = chosen;
    }
  }
  return names;
}

/**
 * "39 BOULEVARD VINCENT AURIOL, 75013 Paris 13e Arrondissement". The street is
 * re-cased on the same terms as a name: the census is a register, not a venue
 * publishing its own address, so its capitals are its data entry, not a choice.
 */
function addressFor(place: FrancePlace): string {
  const street = recaseName(place.street);
  const town = `${place.postcode} ${place.commune}`.trim();
  const address = street ? `${street}, ${town}` : town;
  return address.length <= ADDRESS_MAX ? address : town;
}

/** Is this place already on the map by hand? */
function nearCurated(place: FrancePlace, curated: readonly Spot[]): boolean {
  const here = { lat: place.lat, lng: place.lng };
  return curated.some(
    (spot) => distanceMiles(here, { lat: spot.lat, lng: spot.lng }) <= CURATED_RADIUS_MILES,
  );
}

/**
 * The census as spots. Pure: same snapshot, same rows, same order.
 *
 * `curated` defaults to the hand-researched `SPOTS`; the parameter exists so
 * the tests can prove the exclusion without depending on which French parks a
 * session happened to research.
 */
export function franceSpots(
  rows: readonly FranceSourceRow[] = FRANCE_SOURCE_ROWS,
  curated: readonly Spot[] = SPOTS as readonly Spot[],
): readonly Spot[] {
  const places = collapsePlaces(rows).filter((place) => !nearCurated(place, curated));
  const names = nameSpots(places);
  return places.map((place, i) => ({
    name: names[i]!,
    town: townFor(place.commune),
    country: territoryFor(place.postcode),
    type: place.indoor ? 'Indoor park' : 'Concrete',
    lat: place.lat,
    lng: place.lng,
    sports: ['skate'],
    tags: [],
    status: 'live',
    address: addressFor(place),
    indoor: place.indoor,
    operating: 'unknown',
    source: SOURCE.id,
    licence: SOURCE.licence,
  }));
}
