import {
  COUNTRIES,
  SPOTS,
  SPOT_COUNTRY_BY_CODE,
  SPOT_FEATURE_LIST,
  SPOT_SOURCES,
  distanceMiles,
  importedSpotSports,
  spotFeatureId,
  type ImportedSportsEvidence,
  type Spot,
} from '@landit/core';

import { franceSpots, isGenericName, recaseName } from './france';
import {
  OSM_BIT,
  TNF_FLAG,
  type TnfFlag,
  type WorldOsmRow,
  type WorldSourceRow,
} from './world-source';
import { WORLD_OSM_ROWS, WORLD_SOURCE_ROWS } from './world.data';

/**
 * The world's skateparks — the places on Trucks and Fins' map, matched against
 * OpenStreetMap — to spot rows the seed can write (the owner's call,
 * 2026-09-11, in chat: route B, pages kept out of search, pump tracks count as
 * BMX).
 *
 * **This module is the seeder's and nobody else's**, like `./france.ts`. The
 * rows live in `world.data.ts`, generated by `scripts/import-world.mts`; the
 * app reads the database, and the database is where these become spots.
 *
 * **Everything here is pure**, so each rule has a unit test against hand-made
 * rows and a property test against the real snapshot.
 *
 * ---
 *
 * **Whose data each row is.** Where an OpenStreetMap object sits within 150
 * metres of a park, the point, the name and the address are OpenStreetMap's,
 * under the Open Database Licence — `source: 'osm-tnf'`. Where none does, the
 * row stands on Trucks and Fins' point and name alone — `source: 'tnf'`. On
 * both, the tags, the roof and "gone" come from which of Trucks and Fins' map
 * filters list the park, and that is recorded in the licence column as well
 * (`SPOT_SOURCES` in `@landit/core`). Nothing from Trucks and Fins is prose:
 * it has descriptions and photographs, and none of them is here.
 *
 * **What the data can say, and what it cannot.** A point, a name, a town, and
 * for most parks a filter or two — bowl, mini ramp, pump track, indoor, gone.
 * Nothing about opening hours, and nothing about scooters. So every row goes
 * through `importedSpotSports`: scooter and skate unless a ban is documented,
 * and BMX where the source names it — and, by the owner's call, wherever the
 * park is listed as a pump track, because a pump track is a bike place first.
 * Rows arrive `operating: 'unknown'` unless a source says the park has gone.
 *
 * **The naming rule.** Most names are "*Town* skatepark", which says nothing
 * the card's town line does not already say. A name is *generic* when nothing
 * is left once the words for a facility and the words of its town are taken
 * out — "Rolla skatepark" in Rolla, "Skate Park", "Skateanlage" — and a generic
 * park is called "Skatepark", as a French one is. OpenStreetMap's name is tried
 * before Trucks and Fins', so a mapped name wins. Two parks in one town that
 * would share a name are told apart by an ordinal, in the source's order.
 *
 * **The duplicate rules.** The source map lists a few parks twice, a few
 * metres apart; points within 50 metres of each other are one place, with
 * every filter either copy carried. A place within about 160 metres of a spot
 * already seeded — hand-researched, or from France's census — is that spot,
 * and is dropped: it already has a page somebody checked or a better source.
 *
 * **Then OpenStreetMap on its own (#390; the owner, 2026-09-11, in chat: "go
 * with the recommendations").** OpenStreetMap maps about fifteen thousand
 * skateboarding objects that no park on Trucks and Fins' map claimed. Most are
 * small — a ramp in a playground — so only those whose outline encloses at
 * least **300 m²** are kept, just above a tennis court; pieces of one park
 * within 50 metres are added together first. A point has no outline and is
 * left out, and so is anything marked private. What survives is plain Open
 * Database Licence data (`source: 'osm'`), named by the same rule — "Pump
 * track" rather than "Skatepark" where its name says it is one — and dropped
 * where any spot already seeded, the world rows included, stands within 160
 * metres.
 */

const OSM_SOURCE = SPOT_SOURCES['osm-tnf'];
const TNF_SOURCE = SPOT_SOURCES.tnf;
const OSM_ONLY_SOURCE = SPOT_SOURCES.osm;

/** The owner's floor (#390): smaller than this is a ramp, not a park. */
export const OSM_ONLY_MIN_AREA = 300;

/** `spots.name` is `max: 80` (`1786838400_init_collections.js`). */
const NAME_MAX = 80;
/** The name a generic park gets; the town disambiguates on the card. */
const GENERIC_NAME = 'Skatepark';
/** The source listing one park twice: points this close are one place. */
const SAME_PLACE_MILES = 50 / 1609.344;
/** A place this close to a spot already seeded is that spot — France's radius. */
const EXISTING_RADIUS_MILES = 0.1;

/* --------------------------------------------------------------- words -- */

/**
 * Facility words in the languages the world's parks are named in, on top of
 * the French census's own list (`isGenericName` in `./france.ts`). A word here
 * says what a place is and never which one.
 */
// prettier-ignore
const FACILITY_WORD_LIST = [
  // English
  'skatepark', 'skateparks', 'skateboarding', 'skateboard', 'skating', 'skaters', 'skater',
  'plaza', 'spot', 'skatespot', 'ramp', 'ramps', 'halfpipe', 'miniramp', 'area', 'pumptrack',
  'bike', 'bikes', 'youth', 'community', 'recreation', 'rec', 'center', 'centre', 'ground',
  'grounds', 'reserve', 'domain', 'pitch', 'playground', 'inline', 'scooter', 'scooters', 'dirt',
  'jump', 'jumps', 'trail', 'trails', 'facility', 'town', 'village', 'county', 'memorial',
  // German, Dutch, Scandinavian, Finnish, Polish, Czech
  'skateanlage', 'skaterpark', 'skaterplatz', 'skatebahn', 'skatehalle', 'anlage', 'halle',
  'rollsportanlage', 'platz', 'skatebaan', 'baan', 'skateboardbaan', 'skatebana', 'bana',
  'skateboardbana', 'skateboardpark', 'skateboardanlage', 'skøjtebane', 'skeittipuisto',
  'puisto', 'skeittiparkki', 'wrotowisko', 'skejtpark', 'skejt',
  // Spanish, Portuguese, Italian
  'pista', 'pistas', 'parque', 'parques', 'patinaje', 'patines', 'patins',
  'polideportivo', 'deportivo', 'desportivo', 'municipale', 'comunale',
  // Scripts a Latin fold cannot read: the generic words only, so a real name survives
  'скейтпарк', 'скейт', 'парк', 'スケートパーク', 'スケート', 'パーク', '滑板公园', '滑板场',
  '스케이트파크', '스케이트', '파크',
];

/**
 * The words of a name, lowercase with accents folded — in any script, so a
 * Cyrillic or Japanese name has words too (the census's fold in `./france.ts`
 * keeps Latin letters only).
 */
export function nameWords(text: string): string[] {
  return text
    .normalize('NFKD')
    .replace(/\p{M}/gu, '')
    .toLowerCase()
    .split(/[^\p{L}\p{N}]+/u)
    .filter(Boolean);
}

/**
 * The list folded exactly as a name is, so "Скейтпарк" — whose й a fold splits
 * into и and a mark — is found by the same words it is compared with.
 */
const WORLD_FACILITY_WORDS = new Set(FACILITY_WORD_LIST.flatMap((word) => nameWords(word)));

function isFacilityWord(word: string): boolean {
  if (WORLD_FACILITY_WORDS.has(word) || /^\d+$/.test(word)) return true;
  // A Latin word goes through the census's list as well: "park", "the", "de".
  return /^[a-z0-9]+$/.test(word) && isGenericName(word);
}

/**
 * Does this name say *which* place, or only what kind and which town?
 *
 * Generic: "Rolla skatepark" in Rolla, "Skate Park", "Skateanlage",
 * "Community Skatepark". Not generic: "Finlathen skatepark" in Dundee,
 * "Southbank Undercroft", "駒沢公園スケートパーク".
 */
export function isGenericWorldName(name: string, town: string): boolean {
  const townWords = new Set(nameWords(town));
  return nameWords(name)
    .filter((word) => !townWords.has(word))
    .every(isFacilityWord);
}

/**
 * A kept name, tidied: shouting and whispering re-cased as the census's are,
 * and the lowercase "skatepark" or "pumptrack" the source map appends to its
 * names given a capital — "Finlathen skatepark" → "Finlathen Skatepark".
 */
export function tidyName(name: string): string {
  return recaseName(name.replace(/\s+/g, ' ').trim()).replace(
    /\b(skatepark|pumptrack)\b/g,
    (word) => word.charAt(0).toUpperCase() + word.slice(1),
  );
}

/* ------------------------------------------------------------ places -- */

/** One or more source rows that are one place, the one it is named from first. */
export interface WorldPlace {
  readonly rows: readonly WorldSourceRow[];
  readonly lat: number;
  readonly lng: number;
  readonly town: string;
  /** ISO 3166-1 alpha-2. */
  readonly country: string;
  /** Every filter any of the rows was listed under. */
  readonly flags: number;
  /** Every OpenStreetMap fact any matched row carried. */
  readonly osmBits: number;
  /** Is the place's point and name OpenStreetMap's? */
  readonly matched: boolean;
}

/** Rows with an OpenStreetMap match first, then the source's order. */
const byStrength = (a: WorldSourceRow, b: WorldSourceRow): number =>
  (a[1] ? 0 : 1) - (b[1] ? 0 : 1) || a[0] - b[0];

const CELL = 0.001;
const cellKey = (lat: number, lng: number, size: number): string =>
  `${Math.floor(lat / size)},${Math.floor(lng / size)}`;

/** How many cells either side cover `size` degrees of latitude at this latitude. */
const lngRings = (lat: number): number =>
  Math.ceil(1 / Math.max(0.15, Math.cos((lat * Math.PI) / 180)));

/**
 * Rows within 50 metres of one another are one place. Transitive, so three
 * copies in a line collapse to one; in the source's order, so the same
 * snapshot always gives the same places.
 */
export function collapseWorld(rows: readonly WorldSourceRow[]): readonly WorldPlace[] {
  const sorted = [...rows].sort((a, b) => a[0] - b[0]);
  const parent = sorted.map((_, i) => i);
  const find = (i: number): number => {
    while (parent[i] !== i) {
      parent[i] = parent[parent[i]!]!;
      i = parent[i]!;
    }
    return i;
  };

  const cells = new Map<string, number[]>();
  sorted.forEach((row, i) => {
    const key = cellKey(row[2], row[3], CELL);
    const cell = cells.get(key);
    if (cell) cell.push(i);
    else cells.set(key, [i]);
  });

  sorted.forEach((row, i) => {
    const cy = Math.floor(row[2] / CELL);
    const cx = Math.floor(row[3] / CELL);
    const rings = lngRings(row[2]);
    for (let y = cy - 1; y <= cy + 1; y += 1) {
      for (let x = cx - rings; x <= cx + rings; x += 1) {
        for (const j of cells.get(`${y},${x}`) ?? []) {
          if (j <= i) continue;
          const other = sorted[j]!;
          const d = distanceMiles({ lat: row[2], lng: row[3] }, { lat: other[2], lng: other[3] });
          if (d <= SAME_PLACE_MILES) parent[find(j)] = find(i);
        }
      }
    }
  });

  const groups = new Map<number, WorldSourceRow[]>();
  sorted.forEach((row, i) => {
    const root = find(i);
    const group = groups.get(root);
    if (group) group.push(row);
    else groups.set(root, [row]);
  });

  return [...groups.values()]
    .map((group) => {
      const members = [...group].sort(byStrength);
      const lead = members[0]!;
      return {
        rows: members,
        lat: lead[2],
        lng: lead[3],
        town: lead[10],
        country: lead[11],
        flags: members.reduce((all, row) => all | row[6], 0),
        osmBits: members.reduce((all, row) => all | row[7], 0),
        matched: lead[1] !== '',
      };
    })
    .sort((a, b) => a.rows[0]![0] - b.rows[0]![0]);
}

/** Every existing spot, bucketed by about a kilometre, for the proximity rule. */
function existingIndex(existing: readonly Spot[]): Map<string, Spot[]> {
  const index = new Map<string, Spot[]>();
  for (const spot of existing) {
    const key = cellKey(spot.lat, spot.lng, 0.01);
    const cell = index.get(key);
    if (cell) cell.push(spot);
    else index.set(key, [spot]);
  }
  return index;
}

function nearExisting(
  place: { readonly lat: number; readonly lng: number },
  index: Map<string, Spot[]>,
): boolean {
  const cy = Math.floor(place.lat / 0.01);
  const cx = Math.floor(place.lng / 0.01);
  const rings = lngRings(place.lat);
  for (let y = cy - 1; y <= cy + 1; y += 1) {
    for (let x = cx - rings; x <= cx + rings; x += 1) {
      for (const spot of index.get(`${y},${x}`) ?? []) {
        const d = distanceMiles({ lat: place.lat, lng: place.lng }, spot);
        if (d <= EXISTING_RADIUS_MILES) return true;
      }
    }
  }
  return false;
}

/* --------------------------------------------------------------- names -- */

/**
 * What a place is called before any collision is resolved: the first name, in
 * strength order and OpenStreetMap's before Trucks and Fins', that says which
 * place it is and fits the column.
 */
export function baseName(place: WorldPlace): string {
  for (const row of place.rows) {
    for (const candidate of [row[4], row[5]]) {
      if (!candidate || isGenericWorldName(candidate, place.town)) continue;
      const name = tidyName(candidate);
      if (name.length <= NAME_MAX) return name;
    }
  }
  return GENERIC_NAME;
}

/**
 * Every name unique within its town — against the spots already seeded as
 * well as each other, because the seed's key is name-plus-town and a clash
 * would find the other spot and skip this one. The first place keeps the bare
 * name; later ones count up.
 */
export function nameWorldSpots(
  places: readonly WorldPlace[],
  existing: readonly Pick<Spot, 'name' | 'town'>[] = [],
): readonly string[] {
  return uniqueNames(
    places.map((place) => ({ base: baseName(place), town: place.town })),
    existing,
  );
}

/**
 * Each base name made unique within its town, in order, against the spots
 * already seeded as well as each other — the rule both world tables share.
 */
export function uniqueNames(
  entries: readonly { readonly base: string; readonly town: string }[],
  existing: readonly Pick<Spot, 'name' | 'town'>[] = [],
): readonly string[] {
  const taken = new Map<string, Set<string>>();
  const inTown = (town: string): Set<string> => {
    let names = taken.get(town);
    if (!names) {
      names = new Set();
      taken.set(town, names);
    }
    return names;
  };
  for (const spot of existing) inTown(spot.town).add(spot.name);

  return entries.map(({ base, town }) => {
    const used = inTown(town);
    let name = base;
    for (let n = 2; used.has(name); n += 1) {
      const suffix = ` ${n}`;
      name =
        base.length + suffix.length <= NAME_MAX ? `${base}${suffix}` : `${GENERIC_NAME}${suffix}`;
    }
    used.add(name);
    return name;
  });
}

/* ------------------------------------------------------------ the rest -- */

/**
 * The filters that are features, as the tags `SPOT_FEATURES` explains, in the
 * catalogue's order. "Concrete Park" is the type every outdoor park already
 * has; "Built in the 70s" is history rather than something to ride.
 */
const FLAG_TAGS: readonly (readonly [TnfFlag, string])[] = [
  ['bowl', 'Bowl'],
  ['miniRamp', 'Mini'],
  ['vert', 'Vert'],
  ['halfpipe', 'Halfpipe'],
  ['snakeRun', 'Snake run'],
  ['fullPipe', 'Full pipe'],
  ['pumpTrack', 'Pump track'],
  ['diy', 'DIY'],
];

const FEATURE_ORDER = new Map(SPOT_FEATURE_LIST.map((feature, i) => [feature.id, i]));

export function tagsFor(flags: number): string[] {
  return FLAG_TAGS.filter(([flag]) => flags & TNF_FLAG[flag])
    .map(([, tag]) => tag)
    .sort(
      (a, b) =>
        (FEATURE_ORDER.get(spotFeatureId(a)) ?? Infinity) -
        (FEATURE_ORDER.get(spotFeatureId(b)) ?? Infinity),
    );
}

/** One of `SPOT_TYPES`: under a roof, a street spot, or the outdoor park most are. */
export function typeFor(place: WorldPlace, indoor: boolean): string {
  if (indoor) return 'Indoor park';
  if (place.flags & TNF_FLAG.streetSpot) return 'Street spot';
  return 'Concrete';
}

const BMX_WORD = /\bbmx\b/i;

/**
 * What the sources say about who may ride, for `importedSpotSports`: BMX where
 * OpenStreetMap's `sport` tag or either name says BMX, and wherever the park is
 * listed as a pump track (the owner's call, 2026-09-11, in chat). Nothing here
 * is ever a ban — neither source records one.
 */
export function sportsEvidence(place: WorldPlace): ImportedSportsEvidence {
  const named = place.rows.some((row) => BMX_WORD.test(row[4]) || BMX_WORD.test(row[5]));
  const pumpTrack = (place.flags & TNF_FLAG.pumpTrack) !== 0;
  const tagged = (place.osmBits & OSM_BIT.bmx) !== 0;
  return { bmx: named || pumpTrack || tagged };
}

/** The country name the spots data spells, for an alpha-2 code. */
export function countryName(code: string): string {
  return SPOT_COUNTRY_BY_CODE[code] ?? COUNTRIES[code] ?? code;
}

/**
 * The snapshot as spots. Pure: same snapshot, same existing spots, same rows
 * in the same order.
 *
 * `existing` defaults to what the seed writes before this table — the
 * hand-researched `SPOTS` and France's census — and is a parameter so the
 * tests can prove the rules without depending on either.
 */
export function worldSpots(
  rows?: readonly WorldSourceRow[],
  existing?: readonly Spot[],
): readonly Spot[] {
  if (rows === undefined && existing === undefined) {
    return (snapshotSpots ??= mapWorld(WORLD_SOURCE_ROWS, seededBefore()));
  }
  return mapWorld(rows ?? WORLD_SOURCE_ROWS, existing ?? seededBefore());
}

/** What the seed writes before this table: the researched spots, then France's. */
const seededBefore = (): readonly Spot[] => [...(SPOTS as readonly Spot[]), ...franceSpots()];

/**
 * The snapshot, mapped once per process. Every table in a seed plan and every
 * test that builds one asks for the same twenty-five thousand rows, and a plan
 * is built many times over in a test run; the answer never changes, because
 * everything it is computed from is a constant.
 */
let snapshotSpots: readonly Spot[] | undefined;

function mapWorld(rows: readonly WorldSourceRow[], existing: readonly Spot[]): readonly Spot[] {
  const index = existingIndex(existing);
  const places = collapseWorld(rows).filter((place) => !nearExisting(place, index));
  const names = nameWorldSpots(places, existing);
  return places.map((place, i) => {
    const lead = place.rows[0]!;
    const indoor = (place.flags & TNF_FLAG.indoor) !== 0 || (place.osmBits & OSM_BIT.covered) !== 0;
    const closed = (place.flags & TNF_FLAG.closed) !== 0 || (place.osmBits & OSM_BIT.closed) !== 0;
    const source = place.matched ? OSM_SOURCE : TNF_SOURCE;
    return {
      name: names[i]!,
      town: place.town,
      country: countryName(place.country),
      type: typeFor(place, indoor),
      lat: place.lat,
      lng: place.lng,
      sports: importedSpotSports(sportsEvidence(place)),
      tags: tagsFor(place.flags),
      status: 'live',
      ...(lead[8] ? { address: lead[8] } : {}),
      ...(lead[9] ? { phone: lead[9] } : {}),
      indoor,
      operating: closed ? 'closed' : 'unknown',
      source: source.id,
      licence: source.licence,
    };
  });
}

/* -------------------------------------------------- OpenStreetMap only -- */

/** One or more OpenStreetMap-only outlines that are one place, the largest first. */
export interface OsmOnlyPlace {
  readonly rows: readonly WorldOsmRow[];
  readonly lat: number;
  readonly lng: number;
  readonly town: string;
  readonly country: string;
  readonly osmBits: number;
  /** Every piece's area, added together, in square metres. */
  readonly area: number;
}

/** Items within `miles` of one another, transitively, as groups in input order. */
function groupWithin<T>(
  items: readonly T[],
  at: (item: T) => { readonly lat: number; readonly lng: number },
  miles: number,
): T[][] {
  const parent = items.map((_, i) => i);
  const find = (i: number): number => {
    while (parent[i] !== i) {
      parent[i] = parent[parent[i]!]!;
      i = parent[i]!;
    }
    return i;
  };
  const cells = new Map<string, number[]>();
  items.forEach((item, i) => {
    const { lat, lng } = at(item);
    const key = cellKey(lat, lng, CELL);
    const cell = cells.get(key);
    if (cell) cell.push(i);
    else cells.set(key, [i]);
  });
  items.forEach((item, i) => {
    const here = at(item);
    const cy = Math.floor(here.lat / CELL);
    const cx = Math.floor(here.lng / CELL);
    const rings = lngRings(here.lat);
    for (let y = cy - 1; y <= cy + 1; y += 1) {
      for (let x = cx - rings; x <= cx + rings; x += 1) {
        for (const j of cells.get(`${y},${x}`) ?? []) {
          if (j > i && distanceMiles(here, at(items[j]!)) <= miles) parent[find(j)] = find(i);
        }
      }
    }
  });
  const groups = new Map<number, T[]>();
  items.forEach((item, i) => {
    const root = find(i);
    const group = groups.get(root);
    if (group) group.push(item);
    else groups.set(root, [item]);
  });
  return [...groups.values()];
}

/**
 * Outlines within 50 metres of one another are one place — a park mapped as a
 * bowl and a street section is one park — with their areas added together.
 * Private outlines are taken out first, so one never lends its size to a
 * public neighbour.
 */
export function collapseOsmOnly(rows: readonly WorldOsmRow[]): readonly OsmOnlyPlace[] {
  const open = rows
    .filter((row) => (row[4] & OSM_BIT.private) === 0)
    .sort((a, b) => a[0].localeCompare(b[0]));
  return groupWithin(open, (row) => ({ lat: row[1], lng: row[2] }), SAME_PLACE_MILES)
    .map((group) => {
      const members = [...group].sort((a, b) => b[5] - a[5] || a[0].localeCompare(b[0]));
      const lead = members[0]!;
      return {
        rows: members,
        lat: lead[1],
        lng: lead[2],
        town: lead[8],
        country: lead[9],
        osmBits: members.reduce((all, row) => all | row[4], 0),
        area: members.reduce((sum, row) => sum + row[5], 0),
      };
    })
    .sort((a, b) => a.rows[0]![0].localeCompare(b.rows[0]![0]));
}

const PUMP_TRACK = /\bpump\s*-?\s*track\b|\bpumptrack\b/i;

/** Is this place a pump track, by any piece's name? */
export function isPumpTrack(place: OsmOnlyPlace): boolean {
  return place.rows.some((row) => PUMP_TRACK.test(row[3]));
}

/** The name before collisions: a real one if any piece has it, else what it is. */
export function osmOnlyBaseName(place: OsmOnlyPlace): string {
  for (const row of place.rows) {
    if (!row[3] || isGenericWorldName(row[3], place.town)) continue;
    const name = tidyName(row[3]);
    if (name.length <= NAME_MAX) return name;
  }
  return isPumpTrack(place) ? 'Pump track' : GENERIC_NAME;
}

/**
 * The OpenStreetMap-only table as spots. Pure, and mapped once per process for
 * the snapshot, like `worldSpots`.
 *
 * `existing` defaults to everything the seed writes before this table —
 * researched, French and the world rows — so a place any of them already holds
 * is dropped and no name clashes with theirs.
 */
export function osmOnlySpots(
  rows?: readonly WorldOsmRow[],
  existing?: readonly Spot[],
): readonly Spot[] {
  if (rows === undefined && existing === undefined) {
    return (snapshotOsmOnly ??= mapOsmOnly(WORLD_OSM_ROWS, [...seededBefore(), ...worldSpots()]));
  }
  return mapOsmOnly(rows ?? WORLD_OSM_ROWS, existing ?? [...seededBefore(), ...worldSpots()]);
}

let snapshotOsmOnly: readonly Spot[] | undefined;

function mapOsmOnly(rows: readonly WorldOsmRow[], existing: readonly Spot[]): readonly Spot[] {
  const index = existingIndex(existing);
  const places = collapseOsmOnly(rows).filter(
    (place) => place.area >= OSM_ONLY_MIN_AREA && !nearExisting(place, index),
  );
  const names = uniqueNames(
    places.map((place) => ({ base: osmOnlyBaseName(place), town: place.town })),
    existing,
  );
  return places.map((place, i) => {
    const lead = place.rows[0]!;
    const pumpTrack = isPumpTrack(place);
    const bmx =
      pumpTrack ||
      (place.osmBits & OSM_BIT.bmx) !== 0 ||
      place.rows.some((row) => BMX_WORD.test(row[3]));
    const indoor = (place.osmBits & OSM_BIT.covered) !== 0;
    const closed = (place.osmBits & OSM_BIT.closed) !== 0;
    return {
      name: names[i]!,
      town: place.town,
      country: countryName(place.country),
      type: indoor ? 'Indoor park' : 'Concrete',
      lat: place.lat,
      lng: place.lng,
      sports: importedSpotSports({ bmx }),
      tags: pumpTrack ? ['Pump track'] : [],
      status: 'live',
      ...(lead[6] ? { address: lead[6] } : {}),
      ...(lead[7] ? { phone: lead[7] } : {}),
      indoor,
      operating: closed ? 'closed' : 'unknown',
      source: OSM_ONLY_SOURCE.id,
      licence: OSM_ONLY_SOURCE.licence,
    };
  });
}
