/* Land It. Data layer. Plain JS, exposed on window. */
(function () {
  const SC = [
    { id:"bunny-hop", name:"Bunny Hop", cat:"flat", diff:1, pre:[],
      about:"The foundation under every trick. Crouch, explode upward and pull the bars to your hips so both wheels leave the ground at once. Land it clean and the whole sport opens up.",
      tips:"Practice popping over a crack or a stick on flat ground first. Pull up, don't just jump. The bars do the lifting.",
      fact:"Almost every other trick. 180s, bar spins, grinds. Starts from a solid hop. Nail this before anything else." },
    { id:"tic-tac", name:"Tic Tac", cat:"flat", diff:1, pre:[],
      about:"Lift the front wheel and swing it left, then right, hopping the nose across the ground to build speed without pushing.",
      tips:"Small swings, quick rhythm. Keep your weight over the back wheel the whole time.",
      fact:"It's the first bit of board control most riders learn, and it doubles as a warm-up drill forever after." },
    { id:"manual", name:"Manual", cat:"flat", diff:2, pre:["bunny-hop"],
      about:"Balancing along on the back wheel with the nose held up, rolling as far as you can. Pure control. It lives in your hips and ankles.",
      tips:"Find the balance point and hold it with tiny ankle taps. Look ahead, not down, and you'll ride it way longer.",
      fact:"Manuals get judged on distance. Riders hold them clean across an entire car park in line competitions." },
    { id:"fingerwhip", name:"Fingerwhip", cat:"flat", diff:2, pre:["bunny-hop"],
      about:"Flick the deck around a full whip with your hand instead of your foot while the wheels stay on the ground. A flatground party trick.",
      tips:"Crouch, grab the deck near the headtube and snap your wrist. Let it spin a full lap and stamp it flat under you.",
      fact:"One of the only whips you can learn standing dead still. No hop required to get it round." },
    { id:"hippie-jump", name:"Hippie Jump", cat:"flat", diff:2, pre:["bunny-hop"],
      about:"Roll under a bar or gap, jump straight off the deck and land back on it while the scooter keeps rolling underneath you.",
      tips:"Jump up, not forward. Keep the bars steady with one hand if you need the confidence.",
      fact:"Great confidence builder. It teaches you that the scooter will still be there when you come down." },
    { id:"x-up", name:"X-Up", cat:"flat", diff:1, pre:[],
      about:"Twist the bars a full 180° while airborne (or even standing still) and catch them backwards, then twist back before you need to steer.",
      tips:"Start standing still to learn the catch, then take it into a small hop. Keep your grip loose so the twist doesn't fight your wrists.",
      fact:"One of the first bar tricks most riders learn. It's the natural stepping stone into bar spins." },
    { id:"nose-manual", name:"Nose Manual", cat:"flat", diff:3, pre:["manual"],
      about:"The manual, flipped: rolling forward on the front wheel with the back end lifted behind you.",
      tips:"Way twitchier than a manual. Ease your weight forward, never lunge, and bail backwards if it tips.",
      fact:"Nose manual into a bunny hop out is a classic line-ender on flatground." },
    { id:"180", name:"The 180", cat:"street", diff:2, pre:["bunny-hop"],
      about:"A half rotation: you and the scooter spin 180° and roll away switch (backwards). Wind your shoulders up, then whip them round and let the deck chase your head.",
      tips:"Spot your landing over your shoulder and commit fully. A lazy half-spin is how ankles get rolled.",
      fact:"Land enough of them and 'switch' riding stops feeling alien. Pros drill both frontside and backside until either feels normal." },
    { id:"50-50", name:"50-50 Grind", cat:"street", diff:2, pre:["bunny-hop"],
      about:"Both pegs lock onto a ledge or rail and you slide straight along it. The grind that every other grind is built on top of.",
      tips:"Hop on with your weight centred over the deck and ride it out dead flat. A little wax lets you slide much further.",
      fact:"Get comfy on 50-50s and feebles, smiths and crooked grinds all suddenly start to make sense." },
    { id:"gap", name:"Gap", cat:"street", diff:2, pre:["bunny-hop"],
      about:"Clear a set of stairs, a hole or a road gap in one hop. Speed plus a solid pop and nothing else.",
      tips:"Commit to your speed before the run-up ends. Slowing down mid-approach is what causes casing.",
      fact:"Most street parts are built around one gap the rider spent a whole day on." },
    { id:"icepick", name:"Icepick", cat:"street", diff:3, pre:["50-50"],
      about:"A grind on the back peg only, with the front end of the scooter tipped up above the ledge.",
      tips:"Land back-peg first and keep your shoulders level. Lean too far back and it slips out behind you.",
      fact:"Icepicks look far harder than they are. Which is exactly why riders love them." },
    { id:"feeble", name:"Feeble Grind", cat:"street", diff:4, pre:["50-50"],
      about:"A grind where the back peg rides the ledge or rail while the front wheel hangs out over the edge. Equal parts balance and attitude.",
      tips:"Approach at a slight angle, lock the peg on, keep your weight just behind centre. A little wax makes the ledge way friendlier.",
      fact:"'Feeble' was borrowed straight from BMX and skating. Half of scootering's trick names are inherited from its older cousins." },
    { id:"smith", name:"Smith Grind", cat:"street", diff:4, pre:["feeble"],
      about:"The feeble's mirror: front peg grinds the rail while the back end hangs down on the outside.",
      tips:"Angle in slightly nose-first and keep pressure on that front peg the whole way.",
      fact:"Feeble and smith are the pair that make a rider look like they actually ride street." },
    { id:"180-grind-out", name:"180 Out", cat:"street", diff:4, pre:["50-50","180"],
      about:"Ride out of any grind with a half spin, landing switch off the end of the ledge.",
      tips:"Start the wind-up before the ledge runs out. Turn your head first, everything else follows.",
      fact:"Adding an 'out' to a grind you already have is the cheapest way to double your trick list." },
    { id:"tailwhip", name:"Tailwhip", cat:"park", diff:3, pre:["bunny-hop"],
      about:"The signature scooter move. Hop up, kick the deck through a full 360° loop around the headtube, then stomp it back under your feet mid-air.",
      tips:"Kick with your front foot and keep the bars dead still. Spot the grip tape coming back round before you stamp down.",
      fact:"The tailwhip is basically the symbol of scootering. Your first clean one is a genuine rite of passage." },
    { id:"bar-spin", name:"Bar Spin", cat:"park", diff:3, pre:["bunny-hop"],
      about:"Float off the ground and spin the bars a full 360°, then catch them dead straight before you land. It's all in the wrists and timing.",
      tips:"Throw with your lead hand, catch with the other. Keep your shoulders square. Only the bars should move, not you.",
      fact:"Stack a bar spin onto a tailwhip and you've got a 'ridiculous'. One of scootering's classic combo names." },
    { id:"no-footer", name:"No Footer", cat:"park", diff:3, pre:["bunny-hop"],
      about:"Off a jump you kick both feet off the deck, hang them out in the air, then snap them back on before you land. Pure expression.",
      tips:"Get plenty of height first, push the bars down slightly and keep your eyes locked on the deck the whole time.",
      fact:"Style tricks like this are where riders build their own signature look in the air." },
    { id:"toboggan", name:"Toboggan", cat:"park", diff:3, pre:["no-footer"],
      about:"Grab the deck behind you with one hand and twist the bars, holding the shape at the peak of the jump.",
      tips:"Reach back early. The trick lives at the top of the arc, so pull the shape and hold it a beat.",
      fact:"A grab trick judges reward for how long and how obviously you hold it." },
    { id:"360", name:"The 360", cat:"park", diff:4, pre:["180"],
      about:"A full 360° spin of you and the scooter together off a ramp or jump. Spot it, wind up, and whip the whole rotation the way round.",
      tips:"Wind your upper body before you leave the lip and keep spotting your landing the entire way around.",
      fact:"Stack a 360 with a bar spin or a whip and you are deep into competition-run territory." },
    { id:"heelwhip", name:"Heelwhip", cat:"park", diff:4, pre:["tailwhip"],
      about:"A tailwhip spun the opposite way, kicked round with your heel instead of your toes.",
      tips:"It feels backwards for weeks. Drill the kick standing still against a wall before you take it to a ramp.",
      fact:"Riders who learn heelwhips early tend to end up with the cleanest whip catches." },
    { id:"double-whip", name:"Double Whip", cat:"park", diff:5, pre:["tailwhip"],
      about:"Two full deck rotations in one hop. You need serious height and a fast, flat kick.",
      tips:"Kick harder and later than feels sensible, and don't reach for the first rotation.",
      fact:"The jump from single to double is the biggest single step in park riding." },
    { id:"540", name:"The 540", cat:"park", diff:5, pre:["360"],
      about:"A spin and a half. One and a half rotations before you land, usually off a big transition.",
      tips:"You have to over-rotate the 360 for weeks before this clicks. Keep the wind-up low and tight.",
      fact:"Most riders land their first 540 on a quarter pipe, where the transition does half the work." },
    { id:"whip-to-bar", name:"Whip to Bar", cat:"hybrid", diff:5, pre:["tailwhip","bar-spin"],
      about:"Catch a tailwhip and immediately throw a bar spin in the same air. Two tricks, one jump.",
      tips:"Catch the whip early and high. If the whip is late there's no room left for the bars.",
      fact:"Combos like this are what separate a park run from a park lap." },
    { id:"bri-flip", name:"Bri Flip", cat:"hybrid", diff:5, pre:["tailwhip"],
      about:"A backflip of the deck only: you flick the scooter over underneath you like a kickflip and re-catch it before landing. A proper advanced trick.",
      tips:"Pop hard, flick with your toe and be patient. Wait for the grip to come all the way round before you reach for it.",
      fact:"It's one of the rare tricks named after a person. The rider who first landed it." },
    { id:"scooter-flip", name:"Scooter Flip", cat:"hybrid", diff:5, pre:["bri-flip"],
      about:"The deck rotates a whip and a flip at the same time while you float above it.",
      tips:"Learn the bri flip properly first. This is that motion plus a kick, and it punishes half-commitment.",
      fact:"Slow-motion clips of scooter flips are how most riders finally work out the timing." },
    { id:"backflip", name:"Backflip", cat:"air", diff:5, pre:["360"],
      about:"The big one: a full backward rotation, you and the scooter together, launched off a ramp or jump box. Total commitment required.",
      tips:"Learn it into a foam pit or a resi ramp first. Tuck your knees, throw your head back and spot the landing on the way round.",
      fact:"The earliest scooter backflips went down on the same ramps BMX and MTB riders used. Scooters were the new kids at the park." },
    { id:"frontflip", name:"Front Flip", cat:"air", diff:5, pre:["backflip"],
      about:"A forward rotation off a jump box. Harder to spot than a backflip because the landing hides until the last moment.",
      tips:"Foam pit only until it's automatic. Throw from the chest and keep the scooter pinned to your feet.",
      fact:"Front flips stayed a contest-only trick for years after backflips went mainstream." },
    { id:"superman", name:"Superman", cat:"air", diff:4, pre:["no-footer"],
      about:"Feet off and legs stretched straight out behind you, hanging off the bars at the top of a big air.",
      tips:"You need real height. Push the scooter forward as your legs go back, then pull it home.",
      fact:"Pure spectator trick. It reads from the back of any crowd." },
    { id:"flair", name:"Flair", cat:"air", diff:5, pre:["backflip","360"],
      about:"A backflip with a 180 built in, landing switch out of a quarter pipe.",
      tips:"Only after backflips are boring. Start the twist on the way up, not at the peak.",
      fact:"The flair is the standard 'final trick' of a contest run in every wheeled sport." },
    { id:"tailwhip-flip", name:"Flip Whip", cat:"air", diff:5, pre:["backflip","tailwhip"],
      about:"A full flip with a tailwhip thrown inside it. Backflip or frontflip both count. Top of the pile.",
      tips:"Both halves need to be automatic on their own before you stack them.",
      fact:"There are still only a handful of riders who throw these in a contest run." }
  ];

  /* ---------------- skateboard ---------------- */
  const SK = [
    { id:"sk-ollie", name:"Ollie", cat:"flat", diff:2, pre:[],
      about:"Pop the tail, drag your front foot up the board and level it out in the air. Every other trick in skateboarding is built on top of this one.",
      tips:"Snap the tail hard and slide the front foot straight up to the nose. Jump with the board, don't just flick and hope.",
      fact:"Alan Gelfand did the first one in a pool around 1978. Rodney Mullen took it to flat ground and the whole sport changed." },
    { id:"sk-manual", name:"Manual", cat:"flat", diff:2, pre:[],
      about:"Rolling along on the back two wheels with the nose held up. Balance, not pop.",
      tips:"Find the tipping point and hold it with your ankles. Look where you're going, not at the board.",
      fact:"Manual pads exist in nearly every park because a manual is the glue between two other tricks in a line." },
    { id:"sk-shuvit", name:"Shuvit", cat:"flat", diff:2, pre:[],
      about:"Scoop the board 180° under your feet while you hop. The board spins, you don't.",
      tips:"Scoop back with the tail foot and lift your front foot out of the way. Stay over the board or it shoots out.",
      fact:"It's usually the first trick where a beginner has to trust a board that isn't under them." },
    { id:"sk-fakie-ollie", name:"Fakie Ollie", cat:"flat", diff:2, pre:["sk-ollie"],
      about:"An ollie while rolling backwards. Same motion, opposite feel, and the board wants to fly out in front of you.",
      tips:"Pop slightly later than you think and keep your shoulders over the board.",
      fact:"Fakie tricks are how most skaters end up comfortable riding switch." },
    { id:"sk-pop-shuvit", name:"Pop Shuvit", cat:"flat", diff:3, pre:["sk-ollie","sk-shuvit"],
      about:"A shuvit with an ollie pop in it, so the board spins in the air rather than on the ground.",
      tips:"Pop and scoop in the same motion. Front foot goes up and slightly out to leave room for the spin.",
      fact:"Pop shuvits and kickflips are the two branches the whole flatground trick list grows out of." },
    { id:"sk-180", name:"Frontside 180", cat:"flat", diff:3, pre:["sk-ollie"],
      about:"You and the board turn a half rotation together and roll away fakie, with your chest opening towards the direction of travel.",
      tips:"Wind your shoulders the opposite way first, then unwind. Turn your head and the rest follows.",
      fact:"Backside 180s spin the other way and feel completely different. Most skaters strongly prefer one." },
    { id:"sk-nollie", name:"Nollie", cat:"flat", diff:3, pre:["sk-ollie"],
      about:"An ollie popped off the nose instead of the tail, rolling forwards.",
      tips:"Weight forward, snap the nose, drag the back foot. It's an ollie with your stance rebuilt.",
      fact:"Nollie, switch and fakie versions triple the size of any trick list without adding a single new motion." },
    { id:"sk-kickflip", name:"Kickflip", cat:"flat", diff:3, pre:["sk-ollie"],
      about:"Ollie up and flick the edge of the nose with your toes so the board spins a full barrel roll under you, then catch it with your feet.",
      tips:"Ollie first, flick second. Keep your shoulders square and catch it with the back foot before you look for the ground.",
      fact:"Rodney Mullen invented the flat ground version in 1983. Before that a 'flip' meant flipping the board with your hands." },
    { id:"sk-heelflip", name:"Heelflip", cat:"flat", diff:3, pre:["sk-ollie"],
      about:"The kickflip's mirror: flick off the heel side of the nose so the board rolls the opposite way.",
      tips:"Front foot points slightly inward, flick out with the heel. Land on the bolts, not the middle of the board.",
      fact:"Skaters are almost always noticeably better at one of the two flips, and rarely both." },
    { id:"sk-nose-manual", name:"Nose Manual", cat:"flat", diff:4, pre:["sk-manual"],
      about:"A manual on the front wheels with the tail held up behind you. Twitchier and far less forgiving.",
      tips:"Move your weight, don't lunge. Tiny corrections only.",
      fact:"Nose manual to nollie flip out is the kind of line that decides a game of SKATE." },

    { id:"sk-50-50", name:"50-50 Grind", cat:"street", diff:3, pre:["sk-ollie"],
      about:"Both trucks lock onto a ledge or rail and you grind along it dead straight.",
      tips:"Ollie level with the ledge, land on both trucks at once and stay centred. Wax makes a huge difference.",
      fact:"Skate 50-50s came from roller skating and BMX pegs before they became the base of every ledge trick." },
    { id:"sk-boardslide", name:"Boardslide", cat:"street", diff:3, pre:["sk-ollie"],
      about:"You ollie over the rail and slide along it on the underside of the deck, between the trucks.",
      tips:"Get all the way over before you commit. Turn your shoulders with the slide and keep your weight over the rail.",
      fact:"Boardslide and 50-50 are the two tricks that make everything else on a rail possible." },
    { id:"sk-noseslide", name:"Noseslide", cat:"street", diff:3, pre:["sk-boardslide"],
      about:"Slide along the ledge on the nose of the board with the tail hanging off the side.",
      tips:"Approach parallel and quite close. Keep weight forward the whole slide, then turn out at the end.",
      fact:"Noseslides are the ledge trick most likely to teach you how much wax matters." },
    { id:"sk-5-0", name:"5-0 Grind", cat:"street", diff:4, pre:["sk-50-50"],
      about:"A 50-50 on the back truck only, with the nose held up like a manual on the ledge.",
      tips:"It's a manual and a grind at once. Lock the back truck, hold the balance, ride out flat.",
      fact:"5-0s are named for the American cop show. A lot of skate names come from nowhere sensible." },
    { id:"sk-nosegrind", name:"Nosegrind", cat:"street", diff:4, pre:["sk-50-50"],
      about:"Grinding on the front truck alone with the tail up behind you.",
      tips:"Ollie in nose-first and keep pressure on that front truck. Pop out of the end rather than sliding off.",
      fact:"Nosegrinds are widely considered the hardest of the basic grinds to make look good." },
    { id:"sk-crooked", name:"Crooked Grind", cat:"street", diff:4, pre:["sk-nosegrind"],
      about:"A nosegrind held at an angle so the nose also slides along the ledge. Grind and slide together.",
      tips:"Angle the board in, don't square it up. The nose does half the work.",
      fact:"Short for 'crooked nosegrind'. Most people have only ever called it a k-grind." },
    { id:"sk-tailslide", name:"Tailslide", cat:"street", diff:5, pre:["sk-noseslide"],
      about:"Slide along the ledge on the tail with the nose out over the drop, then turn back out.",
      tips:"Turn a full 90° in the air before you land on it. Half-committing is what makes it hang up.",
      fact:"The tailslide is the trick most skaters name when asked which one finally feels like real skateboarding." },
    { id:"sk-gap", name:"Stair Set", cat:"street", diff:3, pre:["sk-ollie"],
      about:"Ollie a set of stairs or a gap in one go, and roll away from the landing.",
      tips:"Speed is safety here. Bend your knees on impact and keep rolling.",
      fact:"The stair count arms race in the 90s is why almost every skate video has a slam section." },

    { id:"sk-drop-in", name:"Drop In", cat:"park", diff:2, pre:[],
      about:"Set the tail on the coping, lean forward over the front truck and ride down the ramp.",
      tips:"Commit forward. Leaning back is the one thing that guarantees you go down.",
      fact:"It's the single biggest confidence barrier in skateboarding, and it's over in half a second." },
    { id:"sk-rock-to-fakie", name:"Rock to Fakie", cat:"park", diff:2, pre:["sk-drop-in"],
      about:"Ride up the transition, put the middle of the board over the coping, then rock back and roll down fakie.",
      tips:"Push the nose over properly, then lift it back before the front truck catches.",
      fact:"Rock to fakie is where most skaters first learn to trust riding backwards." },
    { id:"sk-axle-stall", name:"Axle Stall", cat:"park", diff:3, pre:["sk-drop-in"],
      about:"Turn and set both trucks on the coping, hold it, then drop back in.",
      tips:"Turn your shoulders early and put the back truck on first.",
      fact:"Every lip trick in a bowl is a variation on stopping on the coping and choosing how to come back." },
    { id:"sk-blunt-fakie", name:"Blunt to Fakie", cat:"park", diff:4, pre:["sk-axle-stall"],
      about:"Stall on the tail with the back wheels above the coping, then pop back in fakie.",
      tips:"Pop off the tail on the way in. Just leaning back drops you straight down the ramp.",
      fact:"Blunts came out of vert skating in the 80s and moved to street ledges a decade later." },
    { id:"sk-hip-transfer", name:"Hip Transfer", cat:"park", diff:4, pre:["sk-drop-in"],
      about:"Take a hip or channel in the park and air from one transition across into another.",
      tips:"Look at the landing ramp, not the gap. Carry more speed than feels comfortable.",
      fact:"Transfers are how a bowl run stops being laps and starts being a line." },

    { id:"sk-varial-flip", name:"Varial Kickflip", cat:"hybrid", diff:4, pre:["sk-kickflip","sk-pop-shuvit"],
      about:"A kickflip and a pop shuvit at once. The board flips and spins 180° in the same hop.",
      tips:"Scoop first, flick second, and catch it late. Rushing the catch is what causes the primo landing.",
      fact:"Varial flips are the classic gateway from single tricks into combination flip tricks." },
    { id:"sk-hardflip", name:"Hardflip", cat:"hybrid", diff:5, pre:["sk-varial-flip"],
      about:"A frontside pop shuvit with a kickflip through it, so the board comes up through your legs.",
      tips:"Front foot scoops down and forward. You have to open your legs and let it come through.",
      fact:"Named because it is, genuinely, hard. One of the few honestly named tricks." },
    { id:"sk-tre-flip", name:"Tre Flip", cat:"hybrid", diff:5, pre:["sk-varial-flip"],
      about:"A 360 pop shuvit with a kickflip in it. The board spins a full lap and flips at the same time.",
      tips:"Scoop much harder than a normal shuvit and flick out at the same moment. Then be patient.",
      fact:"Also called a 360 flip. The trick most often used as the benchmark for 'can actually skate'." },
    { id:"sk-flip-slide", name:"Kickflip Boardslide", cat:"hybrid", diff:5, pre:["sk-kickflip","sk-boardslide"],
      about:"Kickflip into a boardslide, catching the flip exactly as the board meets the rail.",
      tips:"Flip early and low. If the flip is late you land on the rail with nothing under you.",
      fact:"Flip-in tricks are how street skating scores the difference between clean and spectacular." },

    { id:"sk-indy", name:"Indy Grab", cat:"air", diff:3, pre:["sk-drop-in"],
      about:"Air out of the transition and grab the toe edge between your feet with your back hand.",
      tips:"Get proper height first, then reach. Suck your knees up to bring the board to your hand.",
      fact:"The indy is the default grab in every wheeled sport. It's the easiest hand to reach the board with." },
    { id:"sk-backside-air", name:"Backside Air", cat:"air", diff:4, pre:["sk-axle-stall","sk-indy"],
      about:"Fly out above the coping, grab, turn and drop back into the transition.",
      tips:"Look back down the ramp as you turn. Keep the grab until the wheels are pointed at the ramp.",
      fact:"Tony Alva's backside airs in the 70s are why vert skating looks the way it does." },
    { id:"sk-handplant", name:"Handplant", cat:"air", diff:5, pre:["sk-axle-stall"],
      about:"Plant one hand on the coping, invert fully with the board grabbed above you, then come back in.",
      tips:"Learn it on a low ramp with a spotter. The hand goes down before your body commits.",
      fact:"Invert variations carried names like the Andrecht and the Eggplant, after the skaters who first did them." },
    { id:"sk-540", name:"540 McTwist", cat:"air", diff:5, pre:["sk-backside-air"],
      about:"An inverted one and a half rotation out of a vert ramp. Big consequences, big airtime.",
      tips:"Only with pads, a big ramp and a lot of backside airs behind you.",
      fact:"Mike McGill landed the first one in 1984 and it reset what a contest run could contain." }
  ];

  const T = [...SC.map(t => ({ ...t, sport:"scooter" })), ...SK.map(t => ({ ...t, sport:"skate" }))];

  const SPORTS = {
    scooter: { id:"scooter", label:"Scooter", short:"Scooter", color:"#FF5A1F", icon:"scoot",
      kit:"Scooter, helmet, and pads once you're on ramps",
      blurb:"Whips, bar spins and grinds on a stunt scooter" },
    skate:   { id:"skate",   label:"Skateboard", short:"Skate", color:"#246BFF", icon:"board",
      kit:"Skateboard, helmet, and pads for any transition",
      blurb:"Flip tricks, ledges, rails and transition" }
  };
  const SPORT_IDS = ["scooter","skate"];

  const CATS = {
    flat:   { label:"Flat",   color:"#10A06A", blurb:"Ground tricks. Balance and board control" },
    street: { label:"Street", color:"#FF5A1F", blurb:"Ledges, rails, gaps and stairs" },
    park:   { label:"Park",   color:"#246BFF", blurb:"Ramps, boxes and airtime" },
    hybrid: { label:"Hybrid", color:"#8A3BE0", blurb:"Combos and deck flips" },
    air:    { label:"Air",    color:"#E0392B", blurb:"Flips and inverts, big consequences" }
  };

  const TIERS_LABEL = ["Rookie","Easy","Spicy","Gnarly","Pro"];

  /* Four stages, straight off the printed sheet */
  const STAGES = [
    { id:"want",    label:"Want to learn", short:"Want",      color:"#8A3BE0", pct:0 },
    { id:"trying",  label:"Learning",      short:"Learning",  color:"#FF9F1C", pct:25 },
    { id:"some",    label:"Sometimes",     short:"Sometimes", color:"#3AC0FF", pct:55 },
    { id:"most",    label:"Most times",    short:"Most times",color:"#2EC4B6", pct:80 },
    { id:"every",   label:"Every time",    short:"Every time",color:"#10A06A", pct:100 }
  ];

  /* sport:null = counts across everything the rider does */
  const STICKERS = [
    { id:"first-land",  name:"First Land",   sport:null, hue:"#FF5A8A", ico:"check", cond:"Log your first trick",           rule:s=>s.landed>=1 },
    { id:"five-deep",   name:"Five Deep",    sport:null, hue:"#10A06A", ico:"coins", n:5,  cond:"tricks landed",             rule:(s,x)=>s.landed>=x.n },
    { id:"ten-deep",    name:"Ten Deep",     sport:null, hue:"#8A3BE0", ico:"coins", n:10, cond:"tricks landed",             rule:(s,x)=>s.landed>=x.n },
    { id:"week-one",    name:"7 Day Streak", sport:null, hue:"#FFC23F", ico:"flame", n:7,  cond:"days in a row",             rule:(s,x)=>s.streak>=x.n },
    { id:"month-on",    name:"30 Day Streak",sport:null, hue:"#E0392B", ico:"crown", n:30, cond:"days in a row",             rule:(s,x)=>s.streak>=x.n },
    { id:"first-clip",  name:"Caught On Cam",sport:null, hue:"#C46BFF", ico:"cam",   cond:"Upload your first clip",         rule:s=>s.clips>=1 },
    { id:"challenger",  name:"Challenger",   sport:null, hue:"#FF6B6B", ico:"bolt",  cond:"Finish a weekly challenge",      rule:s=>s.challenges>=1 },
    { id:"crew-up",     name:"Crew Up",      sport:null, hue:"#5BA8FF", ico:"users", cond:"Join or start a crew",           rule:s=>s.crew },
    { id:"gnarly",      name:"Gnarly",       sport:null, hue:"#16140F", ico:"skull", cond:"Land a difficulty 5 trick",      rule:s=>s.hardLanded>=1 },
    { id:"both-feet",   name:"Both Feet",    sport:null, hue:"#2EC4B6", ico:"grid",  cond:"Land tricks on both scooter and board", rule:s=>s.bothSports },

    { id:"hop-master",  name:"Hop Master",   sport:"scooter", hue:"#FF9F1C", ico:"scoot", cond:"Every time on the Bunny Hop",   rule:s=>s.byId["bunny-hop"]==="every" },
    { id:"whip-club",   name:"Whip Club",    sport:"scooter", hue:"#246BFF", ico:"star",  cond:"Land a Tailwhip",               rule:s=>["some","most","every"].includes(s.byId["tailwhip"]) },
    { id:"flat-out",    name:"Flat Out",     sport:"scooter", hue:"#2EC4B6", ico:"grid",  cond:"All Flat scooter tricks landed",rule:s=>s.catDone.flat },
    { id:"street-cred", name:"Street Cred",  sport:"scooter", hue:"#FF5A1F", ico:"map",   n:3, cond:"Street scooter tricks landed", rule:(s,x)=>s.catCount.street>=x.n },
    { id:"park-rat",    name:"Park Rat",     sport:"scooter", hue:"#3AC0FF", ico:"home",  n:3, cond:"Park scooter tricks landed",  rule:(s,x)=>s.catCount.park>=x.n },
    { id:"grind-time",  name:"Grind Time",   sport:"scooter", hue:"#9CE05B", ico:"rail",  cond:"Land any scooter grind",        rule:s=>["50-50","feeble","smith","icepick"].some(id=>["some","most","every"].includes(s.byId[id])) },
    { id:"upside",      name:"Upside Down",  sport:"scooter", hue:"#FF3D78", ico:"rotate",cond:"Land a scooter flip trick",     rule:s=>["backflip","frontflip","flair"].some(id=>["some","most","every"].includes(s.byId[id])) },

    { id:"ollie-up",    name:"Ollie Up",     sport:"skate", hue:"#FF9F1C", ico:"scoot", cond:"Every time on the Ollie",       rule:s=>s.byId["sk-ollie"]==="every" },
    { id:"flip-club",   name:"Flip Club",    sport:"skate", hue:"#246BFF", ico:"rotate",cond:"Land a Kickflip",               rule:s=>["some","most","every"].includes(s.byId["sk-kickflip"]) },
    { id:"flat-track",  name:"Flat Tracked", sport:"skate", hue:"#2EC4B6", ico:"grid",  cond:"All Flat skate tricks landed",  rule:s=>s.catDone.flat },
    { id:"ledge-rat",   name:"Ledge Rat",    sport:"skate", hue:"#FF5A1F", ico:"rail",  n:3, cond:"Street skate tricks landed",  rule:(s,x)=>s.catCount.street>=x.n },
    { id:"bowl-rider",  name:"Bowl Rider",   sport:"skate", hue:"#3AC0FF", ico:"home",  n:3, cond:"Park skate tricks landed",    rule:(s,x)=>s.catCount.park>=x.n },
    { id:"coping-time", name:"Coping Time",  sport:"skate", hue:"#9CE05B", ico:"star",  cond:"Land an Axle Stall",            rule:s=>["some","most","every"].includes(s.byId["sk-axle-stall"]) },
    { id:"tre-deep",    name:"Tre Deep",     sport:"skate", hue:"#FF3D78", ico:"bolt",  cond:"Land a Tre Flip",               rule:s=>["some","most","every"].includes(s.byId["sk-tre-flip"]) }
  ];

  /* Rookie riders get the Rookie and Easy tiers of both libraries */
  const FREE_MAX_DIFF = 2;

  const PLANS = [
    { id:"rookie", name:"Rookie", price:"Free", per:"forever", hue:"#10A06A",
      pitch:"Both libraries, up to the Easy tier, tracked properly. No trial, no card.",
      perks:["Scooter and skateboard libraries","Every Rookie and Easy trick","Track every trick through 5 stages","Digital sticker wall","This week's challenge","Spots map and your crew"],
      missing:["Spicy, Gnarly and Pro tricks","Saving clips","Coach view","Real sticker packs"] },
    { id:"shredder", name:"Shredder", price:"£3.99", per:"per month", hue:"#FF5A1F", popular:true,
      pitch:"Unlocks the Spicy, Gnarly and Pro tiers. The whips, flips and tre flips.",
      perks:["Everything in Rookie","Every trick, both sports","Spicy, Gnarly and Pro unlocked","Save clips against any trick","Challenge history + progress stats","Custom printable sheets"],
      missing:["Coach view","Posted sticker packs"] },
    { id:"crew", name:"Crew Pass", price:"£8.99", per:"per month", hue:"#8A3BE0",
      pitch:"Up to 5 riders, plus the grown-ups who drive them to the park.",
      perks:["Everything in Shredder","5 rider accounts","Coach / parent view","Private crew leaderboards","Real sticker pack posted every season","Early access to new tricks"],
      missing:[] }
  ];

  const CREW = [
    { name:"Nia F.",   handle:"@niaflips",  landed:19, streak:12, last:"Feeble Grind", hue:"#FF5A8A", sports:["scooter"],
      privacy:"public",  town:"Liverpool",  stance:"regular", joined:"Mar 2026", stickers:9, crewName:"Ramp Rats" },
    { name:"You",      handle:"@you",       landed:0,  streak:0,  last:"Nothing yet",  hue:"#FFC23F", me:true },
    { name:"Kofi B.",  handle:"@kofib",     landed:14, streak:5,  last:"Bar Spin",     hue:"#3AC0FF", sports:["scooter","skate"],
      privacy:"members", town:"Manchester", stance:"goofy",   joined:"Jan 2026", stickers:7, crewName:"Ramp Rats" },
    { name:"Jonah",    handle:"@jonahwhips",landed:23, streak:31, last:"Double Whip",  hue:"#8A3BE0", sports:["scooter"],
      privacy:"public",  town:"Wigan",      stance:"regular", joined:"Nov 2025", stickers:12, crewName:"Ramp Rats" },
    { name:"Ruby T.",  handle:"@rubyt",     landed:9,  streak:3,  last:"Kickflip",     hue:"#10A06A", sports:["skate"],
      privacy:"members", town:"Sheffield",  stance:"goofy",   joined:"Jun 2026", stickers:5, crewName:"Ramp Rats" },
    { name:"Sam O.",   handle:"@samdoesit", landed:6,  streak:1,  last:"Boardslide",   hue:"#FF9F1C", sports:["skate"],
      privacy:"private", town:"Leeds",      stance:"regular", joined:"Jul 2026", stickers:3, crewName:"Ramp Rats" }
  ];

  const PRIVACY = [
    { id:"public",  label:"Public",      short:"Public",  blurb:"Anyone with the link sees your tricks, stickers and streak. Your surname, email and clips are never shown.",
      other:"Anyone with the link can see this rider's tricks, stickers and streak. Surnames, emails and clips are never shown." },
    { id:"members", label:"Riders only", short:"Riders",  blurb:"Only people signed in to Land It can open your profile. Sensible default for younger riders.",
      other:"This rider only shows their profile to people signed in to Land It." },
    { id:"private", label:"Private",     short:"Private", blurb:"Nobody can open your profile. You still appear on your crew board by name and score.",
      other:"This rider has closed their profile. They still appear on the crew board by name and score." }
  ];

  /* lat/lng drive the map view and the directions link */
  const PARKS = [
    { name:"Rampworx",         town:"Liverpool", type:"Indoor park", dist:"2.4 mi", lat:53.4695, lng:-2.9877, sports:["scooter","skate"], tags:["Foam pit","Resi","Bowl"] },
    { name:"Hillside Bowl",    town:"Sheffield", type:"Concrete",    dist:"5.1 mi", lat:53.3811, lng:-1.4701, sports:["skate"],            tags:["Bowl","Ledges"] },
    { name:"Deansgate Ledges", town:"Manchester",type:"Street spot", dist:"7.8 mi", lat:53.4779, lng:-2.2500, sports:["scooter","skate"], tags:["Ledges","Flat","Rails"] },
    { name:"Adrenaline Alley", town:"Corby",     type:"Indoor park", dist:"11 mi",  lat:52.4930, lng:-0.6890, sports:["scooter","skate"], tags:["Foam pit","Box jump","Mini"] },
    { name:"Southbank",        town:"London",    type:"Street spot", dist:"18 mi",  lat:51.5060, lng:-0.1160, sports:["skate"],            tags:["Flat","Banks"] },
    { name:"Ramp 1",           town:"Wigan",     type:"Indoor park", dist:"9.2 mi", lat:53.5450, lng:-2.6320, sports:["scooter"],          tags:["Ramps","Bowl","Resi"] },
    { name:"Greystone",        town:"Leeds",     type:"Concrete",    dist:"14 mi",  lat:53.7997, lng:-1.5492, sports:["scooter","skate"], tags:["Bowl","Ledges"] }
  ];

  /* One record per week per sport. Dates decide what's live, coming or finished. */
  const CHALLENGES = [
    { id:"sc-30", sport:"scooter", week:"Week 30", title:"Manual Metres", starts:"2026-07-20", ends:"2026-07-26", goal:3, hue:"#FF9F1C",
      reward:"Long Roller sticker", riders:"1,102 riders in", verb:"Log a manual",
      blurb:"Roll a manual the length of a car park. Log three that felt clean." },
    { id:"sc-31", sport:"scooter", week:"Week 31", title:"Grind Week", starts:"2026-07-27", ends:"2026-08-02", goal:3, hue:"#9CE05B",
      reward:"Waxed In sticker", riders:"1,340 riders in", verb:"Log a grind",
      blurb:"Any ledge, any rail, any peg. Three grinds before Sunday." },
    { id:"sc-32", sport:"scooter", week:"Week 32", title:"Bar Spin Blitz", starts:"2026-08-03", ends:"2026-08-09", goal:3, hue:"#8A3BE0",
      reward:"Spun sticker", riders:"1,208 riders in", verb:"Log a bar spin",
      blurb:"Bars all week. Flat, off a kicker, out of a grind. Three of them." },
    { id:"sc-33", sport:"scooter", week:"Week 33", title:"Switch Week", starts:"2026-08-10", ends:"2026-08-16", goal:3, hue:"#3AC0FF",
      reward:"Switch Hitter sticker", riders:"1,284 riders in", verb:"Log a switch trick",
      blurb:"Everything you can already do. Do it rolling backwards. Log three switch tricks before Sunday." },
    { id:"sc-34", sport:"scooter", week:"Week 34", title:"No Hander Week", starts:"2026-08-17", ends:"2026-08-23", goal:3, hue:"#FF5A1F",
      reward:"Hands Off sticker", riders:"Opens Monday", verb:"Log a no hander",
      blurb:"Let go of something. No footers count, no handers count double." },
    { id:"sc-35", sport:"scooter", week:"Week 35", title:"Park Lap", starts:"2026-08-24", ends:"2026-08-30", goal:1, hue:"#10A06A",
      reward:"Full Lap sticker", riders:"Opens in two weeks", verb:"Log a full lap",
      blurb:"One clean lap of your local, no put downs. Film it or it didn't happen." },

    { id:"sk-30", sport:"skate", week:"Week 30", title:"Manual Metres", starts:"2026-07-20", ends:"2026-07-26", goal:3, hue:"#FF9F1C",
      reward:"Long Roller sticker", riders:"1,880 riders in", verb:"Log a manual",
      blurb:"Hold a manual the length of the pad. Three that you actually rode out." },
    { id:"sk-31", sport:"skate", week:"Week 31", title:"Ledge Week", starts:"2026-07-27", ends:"2026-08-02", goal:3, hue:"#9CE05B",
      reward:"Waxed In sticker", riders:"2,240 riders in", verb:"Log a ledge trick",
      blurb:"Anything on a ledge. Slides count, grinds count, hitting it and bailing does not." },
    { id:"sk-32", sport:"skate", week:"Week 32", title:"Flip In Flip Out", starts:"2026-08-03", ends:"2026-08-09", goal:3, hue:"#8A3BE0",
      reward:"In And Out sticker", riders:"1,975 riders in", verb:"Log a flip trick",
      blurb:"A flip into something or out of something. Three of them, any obstacle." },
    { id:"sk-33", sport:"skate", week:"Week 33", title:"Fakie Week", starts:"2026-08-10", ends:"2026-08-16", goal:3, hue:"#FF9F1C",
      reward:"Backwards sticker", riders:"2,067 riders in", verb:"Log a fakie trick",
      blurb:"Take three tricks you already have and land them rolling fakie. Nollie versions count double." },
    { id:"sk-34", sport:"skate", week:"Week 34", title:"Coping Week", starts:"2026-08-17", ends:"2026-08-23", goal:3, hue:"#246BFF",
      reward:"On The Coping sticker", riders:"Opens Monday", verb:"Log a lip trick",
      blurb:"Get to the top of the transition and stop there. Stalls, rocks, grinds." },
    { id:"sk-35", sport:"skate", week:"Week 35", title:"Stair Count", starts:"2026-08-24", ends:"2026-08-30", goal:1, hue:"#E0392B",
      reward:"Down The Set sticker", riders:"Opens in two weeks", verb:"Log a set",
      blurb:"One set of stairs, rolled away. Any size, and three is not braver than one." }
  ];

  const STANCES = [
    { id:"regular", label:"Regular", sub:"Left foot forward" },
    { id:"goofy",   label:"Goofy",   sub:"Right foot forward" },
    { id:"switch",  label:"Both",    sub:"Comfortable either way" }
  ];

  const EVENTS = [
    { id:"e1", name:"Northern Jam", kind:"Comp", town:"Manchester", venue:"Projekts MCR", date:"2026-08-29", sports:["scooter","skate"],
      level:"All levels", price:"£8 entry", spots:"40 riders", blurb:"Jam format, open practice all day, best trick at four." },
    { id:"e2", name:"Rampworx Open", kind:"Comp", town:"Liverpool", venue:"Rampworx", date:"2026-09-05", sports:["scooter"],
      level:"Under 14 and open", price:"£12 entry", spots:"60 riders", blurb:"Two age brackets, qualifying runs then a final. Helmets required." },
    { id:"e3", name:"Girls Skate Session", kind:"Session", town:"Sheffield", venue:"Hillside Bowl", date:"2026-09-07", sports:["skate"],
      level:"Beginner friendly", price:"Free", spots:"Drop in", blurb:"Coached session, boards and pads to borrow. Runs monthly." },
    { id:"e4", name:"Adrenaline Alley Comp", kind:"Comp", town:"Corby", venue:"Adrenaline Alley", date:"2026-09-19", sports:["scooter","skate"],
      level:"Open", price:"£15 entry", spots:"80 riders", blurb:"The big one. Foam pit open before the final." },
    { id:"e5", name:"Learn To Drop In", kind:"Class", town:"Leeds", venue:"Greystone", date:"2026-09-21", sports:["skate"],
      level:"Total beginners", price:"£5", spots:"12 places", blurb:"One hour, one skill. You will drop in by the end of it." },
    { id:"e6", name:"Whip Battle", kind:"Comp", town:"Wigan", venue:"Ramp 1", date:"2026-10-03", sports:["scooter"],
      level:"Intermediate up", price:"£10 entry", spots:"32 riders", blurb:"Head to head brackets. One whip trick each, no repeats." }
  ];

  const NOTICES = [];

  window.LANDIT = { T, SC, SK, SPORTS, SPORT_IDS, CATS, TIERS_LABEL, STAGES, STICKERS, PLANS, FREE_MAX_DIFF, CREW, PRIVACY, PARKS, CHALLENGES, EVENTS, NOTICES, STANCES };
})();
